### ISSUE TITLE
Element 'plugin', attribute 'sortorder': The attribute 'sortorder' is not allowed.

### ISSUE THREAD

**Issue by ray-moncada** [bharat2762/magento2.3.x-admin-low-stock-notification#1]
Magento 2.3
The file /app/code/Bharat/LowStockNotification/etc/di.xml

remove sortorder attribute from plugin element.

Thanks for sharing the extension.

**Comment by manish0345** [comment]
Hi,

Its Spell mistake, instead of removing sortorder, change it to "sortOrder".
Or you can remove also the attribute.

Thanks

**Comment by bharat2762** [comment]
Thanks for the support.
https://github.com/bharat2762/magento2.3.x-admin-low-stock-notification/commit/e63086bed83eb1ccde229771dec2d88cb4ac8944 Issue fixed
