### ISSUE TITLE
Invalid template file

### ISSUE THREAD

**Issue by manish0345** [bharat2762/magento2.3.x-admin-low-stock-notification#2]
Hi,

I am facing below issue, can you please check and let me know about it.

Invalid template file: 'Bharat_LowStockNotification::notifications/low_stock_single_alert.phtml' in module: '' block's name: 'magento\framework\view\element\template_0'

**Comment by manish0345** [comment]
And here the solution for above issue.
adminhtml/templates/notifications/low_stock_single_alert.phtml

You need to create file as shown above path.

**Comment by bharat2762** [comment]
Hi @manish0345 
We have resolve this issue:https://github.com/bharat2762/magento2.3.x-admin-low-stock-notification/commit/386f31709c7ca0700ccb40ca992a67b60ddf1f6b
