### ISSUE TITLE
Not receiving email notifications

### ISSUE THREAD

**Issue by unhyphenatedanarchy** [bharat2762/magento2.3.x-admin-low-stock-notification#3]
I have configured your extension in Magento 2.3.4 to email my gmail address and I am not receiving low stock notification emails at that email address or in my spam folder.

**Comment by adeelmughal4u** [comment]
Same issue, not receiving email.

**Comment by jeredmilla** [comment]
Yes same issue, not receiving any email notification.

**Comment by xpec-gaguirre** [comment]
I fixed the module, you can download here:
[MageDad.zip](https://github.com/bharat2762/magento2.3.x-admin-low-stock-notification/files/5285466/MageDad.zip)

**Comment by bharat2762** [comment]
@adeelmughal4u @xpec-gaguirre @jeredmilla @unhyphenatedanarchy 
We have updated extension. sorry for inconvenience.
