### ISSUE TITLE
Issue with Magento 2.3.5-p2

### ISSUE THREAD

**Issue by rupertbyers-ec** [bharat2762/magento2.3.x-admin-low-stock-notification#4]
I get this when creating an order with a product that will call the extension to work (I.E. Within the low stock value. In my case "under 10")

Fatal error: Uncaught Error: Call to undefined method Magento\Framework\Mail\EmailMessage\Interceptor::addPartsToBody() in /var/www/html/app/code/MageDad/LowStockNotification/Mail/Template/TransportBuilder.php:37 Stack trace: 

#0 /var/www/html/vendor/magento/framework/Mail/Template/TransportBuilder.php(337): MageDad\LowStockNotification\Mail\Template\TransportBuilder->prepareMessage() 
#1 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\Mail\Template\TransportBuilder->getTransport() 
#2 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): MageDad\LowStockNotification\Mail\Template\TransportBuilder\Interceptor->___callParent('getTransport', Array) 
#3 /var/www/html/vendor/fooman/emailattachments-implementation-m2/src/Plugin/TransportBuilder.php(41): MageDad\LowStockNotification\Mail\Template\TransportBuilder\Interceptor->Magento\Framework\Interception\{closure}() 
#4 /var/www/html/vendor/magento/framework/Interce in /var/www/html/app/code/MageDad/LowStockNotification/Mail/Template/TransportBuilder.php on line 37

**Comment by bharat2762** [comment]
@rupertbyers-ec 
We fixed this issue.
